name: climada_env
channels:
  - defaults
dependencies:
  - cartopy=0.16.0
  - dill==0.2.7.1
  - geos=3.6.2
  - h5py=2.7.1
  - ipython=6.4.0
  - jsonschema=2.6.0
  - jupyter_client=5.2.3
  - jupyter_core=4.4.0
  - matplotlib=2.2.2
  - mccabe=0.6.1
  - notebook=5.5.0
  - numba=0.37.0
  - numpy=1.14.2
  - pandas=0.23.0
  - pip=10.0.1
  - proj4=4.9.3
  - pylint=1.8.4
  - pyproj=1.9.5.1
  - python=3.6.5
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - setuptools=39.1.0
  - shapely=1.6.4
  - sphinx=1.7.4
  - spyder=3.2.8
  - xarray==0.10.2
  - xlrd=1.1.0
  - pip:
    - coverage==4.4.2
    - multiprocess==0.70.5
    - pathos==0.2.1
    - pint==0.8.1
    - pox==0.2.3
    - ppft==1.6.4.7.1
    - xmlrunner==1.7.7

