name: climada
channels:
  - defaults
dependencies:
  - alabaster=0.7.10
  - asn1crypto=0.22.0
  - astroid=1.5.3
  - babel=2.5.0
  - bleach=2.0.0
  - ca-certificates=2017.08.26
  - cartopy=0.16.0
  - certifi=2018.1.18
  - cffi=1.10.0
  - chardet=3.0.4
  - cryptography=2.0.3
  - cycler=0.10.0
  - dill==0.2.7.1
  - decorator=4.1.2
  - docutils=0.14
  - entrypoints=0.2.3
  - expat=2.2.5
  - freetype=2.8
  - geos=3.6.2
  - h5py=2.7.1
  - hdf5=1.10.1
  - html5lib=0.999999999
  - icu=58.2
  - idna=2.6
  - imagesize=0.7.1
  - intel-openmp=2018.0.0
  - ipykernel=4.6.1
  - ipython=6.1.0
  - ipython_genutils=0.2.0
  - isort=4.2.15
  - jedi=0.10.2
  - jinja2=2.9.6
  - jpeg=9b
  - jsonschema=2.6.0
  - jupyter_client=5.2.2
  - jupyter_core=4.4.0
  - lazy-object-proxy=1.3.1
  - libiconv=1.15
  - libpng=1.6.32
  - libtiff=4.0.9
  - libxml2=2.9.7
  - libxslt=1.1.32
  - lxml=4.1.1
  - markupsafe=1.0
  - matplotlib=2.1.1
  - mccabe=0.6.1
  - mistune=0.8.1
  - mkl=2018.0.1
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - notebook=5.3.1
  - numpy=1.13.3
  - numpydoc=0.7.0
  - olefile=0.45.1
  - openssl=1.0.2n
  - owslib=0.16.0
  - pandas=0.21.1
  - pandoc=1.19.2.1
  - pandocfilters=1.4.2
  - pcre=8.41
  - pexpect=4.2.1
  - pickleshare=0.7.4
  - pillow=5.0.0
  - pip=9.0.1
  - proj4=4.9.3
  - prompt_toolkit=1.0.15
  - psutil=5.4.0
  - pycodestyle=2.3.1
  - pycparser=2.18
  - pyepsg=0.3.2
  - pyflakes=1.6.0
  - pygments=2.2.0
  - pylint=1.7.4
  - pyopenssl=17.2.0
  - pyparsing=2.2.0
  - pyproj=1.9.5.1
  - pyqt=5.6.0
  - pyshp=1.2.12
  - pysocks=1.6.7
  - python=3.6.3
  - python-dateutil=2.6.1
  - pytz=2017.2
  - pyzmq=16.0.2
  - qt=5.6.2
  - qtawesome=0.4.4
  - qtconsole=4.3.1
  - qtpy=1.3.1
  - requests=2.18.4
  - rope=0.10.5
  - scikit-learn=0.19.1
  - scipy=1.0.0
  - send2trash=1.4.2
  - setuptools=36.5.0
  - shapely=1.6.2
  - simplegeneric=0.8.1
  - sip=4.18.1
  - six=1.11.0
  - snowballstemmer=1.2.1
  - sphinx=1.6.3
  - sphinxcontrib=1.0
  - sphinxcontrib-websupport=1.0.1
  - spyder=3.2.4
  - sqlite=3.20.1
  - terminado=0.8.1
  - testpath=0.3.1
  - tk=8.6.7
  - tornado=4.5.2
  - traitlets=4.3.2
  - typing=3.6.2
  - urllib3=1.22
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.29.0
  - wrapt=1.10.11
  - xarray==0.10.2
  - xlrd=1.1.0
  - xz=5.2.3
  - zeromq=4.2.2
  - zlib=1.2.11
  - pip:
    - coverage==4.4.2
    - multiprocess==0.70.5
    - pathos==0.2.1
    - pint==0.8.1
    - pox==0.2.3
    - ppft==1.6.4.7.1
    - xmlrunner==1.7.7

